# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Test
          command: mvn test

      - run:
          name: Run Tests with Maven
          command: mvn clean verify

      - run:
          name: Upload Coverage to Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN

workflows:
  sample:
    jobs:
      - build-and-test
