# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  check:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Test
          command: mvn test

      - run:
          name: Run Tests with Maven
          command: mvn clean verify

      - run:
          name: Upload Coverage to Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN

      - run:
          name: Run Checkstyle
          command: mvn -U -e checkstyle:check

      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build-and-test:
    jobs:
      - check
