name: Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.merged == true  # Check if PR was merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Generate Javadoc
        run: mvn -B javadoc:javadoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DOC_TOKEN }}
          publish_dir: ./target/site/apidocs  # Path to the generated Javadoc